### Listar productos

GET http://localhost:3000/api/products

### Crear un producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Mouse",
  "price": 80.90
}

### Crear un usuario de prueba
POST https://mockmentor.onrender.com/auth/register
Content-Type: application/json

{
  "firstname": "Victor",
  "lastname": "G03",
  "email": "victorg03@gmail.com",
  "password": "mipassword"
}

### Login con el usuario de prueba
POST https://mockmentor.onrender.com/auth/login
Content-Type: application/json

{
  "email": "victorg03@gmail.com",
  "password": "mipassword"
}